# Generated by Django 3.0.6 on 2020-05-23 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('license_plate', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('line', models.CharField(max_length=200)),
                ('cylinder_head', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_date', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(2000)])),
                ('uploadedImage', models.ImageField(null=True, upload_to='Upload/')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Manufacture')),
            ],
        ),
    ]
